name: Send Daily Poll - Meal Plan (Company) Morning and Afternoon

on:
  schedule:
    # UTC cron: 11:15 AM
    - cron: '15 11 * * *' 
  workflow_dispatch: # can run manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r projetos/data_science/bots/habitflow_telegram/requirements.txt

      - name: Run bot script
        env:
          # Secrets
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python projetos/data_science/bots/habitflow_telegram/scripts/main.py